# Setup
title:               Shriya Meenakshisundaram
tagline:             
description:         
url:                 http://25shriya.github.io
baseurl:             ''
paginate:            5
permalink:           pretty


# About/contact
author:
  name:              Shriya Meenakshisundaram
  url:               https://25shriya.github.io
  email:             25shriya@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
